1.11 algorithms summary tasks
AlexandraPopovaz/Simple-operations-in-js-ts pull request #11
Opened 2022-12-14 15:25 UTC by AlexandraPopovaz

2022-12-14 15:33 UTC, viraxslot commented on src/algorithms-task3.ts
> +            lowerStr += strLowerCase[i];
No need to add chars to the new string, you can just increase the resulting amount.

2022-12-14 15:51 UTC, viraxslot requested changes

2022-12-14 15:51 UTC, viraxslot commented on src/algorithms-task3.ts
> +Задача 3.
English only please

2022-12-14 15:51 UTC, viraxslot commented on src/algorithms-task2.ts
> +function example(stringExample2: string): Record<string, number> {
stringExample2 - I'd rename the function parameter to "param" or something like this.

2022-12-14 15:51 UTC, viraxslot commented on src/algorithms-task2.ts
> +        if (result.hasOwnProperty(stringExample2[i])) {
You can use `hasOwn` instead, it's the same but shorter.

2022-12-14 15:51 UTC, viraxslot commented on src/algorithms-task3.ts
> +function getString(myObj: Record<string, number>): string | null {
Same, I'd name the parameter in a neutral way: param.

2022-12-14 15:51 UTC, viraxslot commented on src/algorithms-task3.ts
> +        result += el;
I don't understand why you're adding an element to the result here.

2022-12-14 15:51 UTC, viraxslot commented on src/algorithms-task3.ts
> +    amountOfLowerChars: number | null;
I think your functions can't (and shouldn't) return null.

2022-12-14 15:51 UTC, viraxslot commented on src/algorithms-task3.ts
> +    const objResult: stringResult = {
You can write just return {} and that's it. You can set the return type in the function declaration. But I believe ts can handle this type by itself.

2022-12-14 15:51 UTC, viraxslot commented on src/composite-types.ts
> +let sizeOne = 2,
I'd suggest not using the comma operator. Just 2 strings, 2 let-s. Less error-prone.

2022-12-15 10:06 UTC, AlexandraPopovaz commented on src/composite-types.ts
> +let sizeOne = 2,
Fixed

2022-12-15 10:06 UTC, AlexandraPopovaz commented on src/algorithms-task3.ts
> +    const objResult: stringResult = {
Sorry, don't understand it

2022-12-15 10:07 UTC, AlexandraPopovaz commented on src/algorithms-task3.ts
> +    amountOfLowerChars: number | null;
Fixed

2022-12-15 10:07 UTC, AlexandraPopovaz commented on src/algorithms-task3.ts
> +        result += el;
Because the Result should be a string consists of keys=elements

2022-12-15 10:10 UTC, AlexandraPopovaz commented on src/algorithms-task2.ts
> +        if (result.hasOwnProperty(stringExample2[i])) {
Not the same, in this case I need to change type from "number" to "any" - is it an appropriate way here?
![image](https://user-images.githubusercontent.com/94701044/207831795-a763334f-3dbf-4648-be92-16f2c72f7ce2.png)

2022-12-15 10:10 UTC, AlexandraPopovaz commented on src/algorithms-task3.ts
> +            lowerStr += strLowerCase[i];
Thanks, fixed it

2022-12-15 10:10 UTC, AlexandraPopovaz commented on src/algorithms-task3.ts
> +Задача 3.
Done

2022-12-19 12:31 UTC, AlexandraPopovaz commented on src/algorithms-task3.ts
> +        result += el;
Thanks! Fixed

2022-12-19 15:22 UTC, viraxslot approved these changes

2022-12-19 15:24 UTC, merged