1.14 Created functions using fakerjs
AlexandraPopovaz/Simple-operations-in-js-ts pull request #18
Opened 2023-01-02 19:27 UTC by AlexandraPopovaz

2023-01-04 17:32 UTC, viraxslot commented on src/file-test-conflict-solving.ts
> -let nn = 5;
Do you need this file in the PR?

2023-01-04 17:32 UTC, viraxslot commented on src/fakerjs.ts
> +function randomObj(paramShortStr: number, paramLongStr: number) {
shortStrLength maybe? `param` is not necessarily will be in the parameter name :) 
10 and 50 should be default values for string lengths. You have no default values at the moment. "default value" means that you can call the function without parameters and it will work in this case.

2023-01-04 18:19 UTC, AlexandraPopovaz commented on src/file-test-conflict-solving.ts
> -let nn = 5;
This file was deleted
![image](https://user-images.githubusercontent.com/94701044/210622760-3bd182ad-5da9-4e5f-9cab-76c62c1c80eb.png)

2023-01-04 19:26 UTC, AlexandraPopovaz commented on src/fakerjs.ts
> +function randomObj(paramShortStr: number, paramLongStr: number) {
Thanks! Was trying to fix it

2023-01-11 08:04 UTC, viraxslot requested changes

2023-01-11 08:04 UTC, viraxslot commented on tests/fakerjs-task1.spec.ts
> +        expect(getResult).toBeNull;
toBeNull is a function, not property, you need to call it. And you don't need "as any" then. This test is false positive, it doesn't check anything, please be attentive with that. 

https://jestjs.io/docs/expect#tobenull

2023-01-11 08:04 UTC, viraxslot commented on tests/fakerjs-task1.spec.ts
> +        expect(getResult).toBeNull;
Same here

2023-01-11 08:04 UTC, viraxslot commented on tests/fakerjs-task2.spec.ts
> +        expect(typeof result.firstName).toBe("string");
Usually, we write tests in "flat" manner, so it means no conditions or loops. But here if your object would have 10-15 fields or so I'd iterate through them and check 1 same type.

2023-01-12 18:32 UTC, AlexandraPopovaz commented on src/fakerjs.ts
> +export { randomObj, createStudent };
Ok, decided to change

2023-01-12 18:32 UTC, AlexandraPopovaz commented on tests/fakerjs-task1.spec.ts
> +    it("should return short string value as a string with length is equal 5", () => {
Done

2023-01-12 18:32 UTC, AlexandraPopovaz commented on tests/fakerjs-task1.spec.ts
> +        expect(getResult).toBeNull;
Thanks! Fixed it

2023-01-12 18:32 UTC, AlexandraPopovaz commented on tests/fakerjs-task1.spec.ts
> +        expect(getResult).toBeNull;
Done

2023-01-13 12:45 UTC, viraxslot approved these changes

2023-01-13 12:50 UTC, merged