1.2 Tests for Jest
AlexandraPopovaz/Simple-operations-in-js-ts pull request #2
Opened 2022-07-25 11:14 UTC by AlexandraPopovaz

2022-07-31 14:50 UTC, viraxslot requested changes

2022-07-31 14:50 UTC, viraxslot commented on README.md
>  ### How to run the project
I'd change the title then. Your description is more about "what were done".

2022-07-31 14:50 UTC, viraxslot commented on jest.config.js
> +  testMatch: ["**/testForJest/**/*.+(ts|js)"]
I'm not sure you need "+" here. Please see the description here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Quantifiers

2022-07-31 14:50 UTC, viraxslot commented on myTests/setupF.ts
> +// export const sum = function (a:number, b:number) {
Please keep the code clean. No commented code should be present. I know we're learning, but it's about your coding habits.

2022-07-31 14:50 UTC, viraxslot commented on myTests/setupF.ts
> +function sum(a: number, b: number) {
It's better to use the same export approach everywhere.

2022-07-31 14:50 UTC, viraxslot commented on myTests/setupF.ts
> +    //return ["Sessna", "Parks", "Fairchild"];
Unnecessary comment here too

2022-07-31 14:50 UTC, viraxslot commented on myTests/useF.ts
> +import * as func from './setupF'
"*" already means you've exported everything. The next line is redundant.

2022-07-31 14:50 UTC, viraxslot commented on node_modules/.package-lock.json
> +    "node_modules/@ampproject/remapping": {
Please add "node_modules" to .gitignore, you shouldn't add this folder into git. My bad, I didn't notice that before.

2022-07-31 14:50 UTC, viraxslot commented on testForJest/testDeletion.ts
> +describe("Positive result", () => {
I already explained that, but again: please do 1 common `describe` and nest everything into it. It'll be easier when you'll decide to use hooks (before, beforeEach, etc.). And no need to add `describe` if there is only 1 test.

2022-07-31 14:50 UTC, viraxslot commented on testForJest/testDeletion.ts
> +import { divide } from "../myTests/setupF";
Usually, we name test files like `my-test.spec.ts` or `my-test.test.ts`. Easier to distinguish these files from others. And I'd say I prefer kebab-case in file naming, easier to read I'd say. But it's not an error, of course.

2022-07-31 14:50 UTC, viraxslot commented on testForJest/testDeletion.ts
> +      expect(getDelitionZero).not.toBe(0);
You can be more specific here.

2022-07-31 14:50 UTC, viraxslot commented on testForJest/testDeletion.ts
> +      expect(getDelitionDefined).not.toBeUndefined();
I see no difference between this test and the first one. You can use both matchers in 1 test case.

2022-07-31 14:50 UTC, viraxslot commented on testForJest/testDeletion.ts
> +      expect(getDelitionNull).not.toBeNull();
Same here, you shouldn't create a separate case for this check.

2022-07-31 14:50 UTC, viraxslot commented on testForJest/testDeletion.ts
> +      expect(getDelitionInteger).toBeGreaterThan(3);
Your checks should be as strict as possible. I believe you wanted to try different matchers, but this check is really bad here.

2022-07-31 14:50 UTC, viraxslot commented on testForJest/testDeletion.ts
> +      expect(getDelitionInteger).toBeCloseTo(1.2);
Same here. Please check exact values :)

2022-07-31 14:50 UTC, viraxslot commented on testForJest/testPlaneName.ts
> +describe("Check match", () => {
Please don't forget to change titles

2022-07-31 15:21 UTC, viraxslot commented on testForJest/testDeletion.ts
> +describe("Negative result", () => {
Please think about other negative checks. Different types, for example.

2022-08-01 21:18 UTC, AlexandraPopovaz commented on README.md
>  ### How to run the project
Fixed

2022-08-01 21:18 UTC, AlexandraPopovaz commented on jest.config.js
> +  testMatch: ["**/testForJest/**/*.+(ts|js)"]
Done

2022-08-01 21:18 UTC, AlexandraPopovaz commented on myTests/setupF.ts
> +// export const sum = function (a:number, b:number) {
Thanks! Fixed

2022-08-01 21:18 UTC, AlexandraPopovaz commented on myTests/setupF.ts
> +function sum(a: number, b: number) {
Fixed

2022-08-01 21:18 UTC, AlexandraPopovaz commented on myTests/setupF.ts
> +    //return ["Sessna", "Parks", "Fairchild"];
Fixed

2022-08-01 21:19 UTC, AlexandraPopovaz commented on myTests/useF.ts
> +import * as func from './setupF'
Thanks! Missed it

2022-08-01 21:22 UTC, AlexandraPopovaz commented on node_modules/.package-lock.json
> +    "node_modules/@ampproject/remapping": {
I was trying - removed "node_modules" folder and removed this name from "git ignore" file, after that I added the folder again and added it into git ignore. But I'm not sure that it's fine now

2022-08-01 21:22 UTC, AlexandraPopovaz commented on testForJest/testDeletion.ts
> +describe("Positive result", () => {
Thanks! Done

2022-08-01 21:22 UTC, AlexandraPopovaz commented on testForJest/testDeletion.ts
> +import { divide } from "../myTests/setupF";
Thank you, fixed it

2022-08-01 21:23 UTC, AlexandraPopovaz commented on testForJest/testDeletion.ts
> +      expect(getDelitionZero).not.toBe(0);
Removed this check

2022-08-01 21:23 UTC, AlexandraPopovaz commented on testForJest/testDeletion.ts
> +      expect(getDelitionDefined).not.toBeUndefined();
Fixed

2022-08-01 21:23 UTC, AlexandraPopovaz commented on testForJest/testDeletion.ts
> +      expect(getDelitionNull).not.toBeNull();
Ok, fixed

2022-08-01 21:23 UTC, AlexandraPopovaz commented on testForJest/testDeletion.ts
> +      expect(getDelitionInteger).toBeGreaterThan(3);
Removed it, thanks!

2022-08-01 21:23 UTC, AlexandraPopovaz commented on testForJest/testDeletion.ts
> +      expect(getDelitionInteger).toBeCloseTo(1.2);
Fixed

2022-08-01 21:23 UTC, AlexandraPopovaz commented on testForJest/testPlaneName.ts
> +describe("Check match", () => {
Fixed

2022-08-01 21:24 UTC, AlexandraPopovaz commented on testForJest/testDeletion.ts
> +describe("Negative result", () => {
Added some checks, thanks!

2022-08-02 13:15 UTC, viraxslot requested changes

2022-08-02 13:15 UTC, viraxslot commented on test-jest/test-deletion.spec.ts
> +import { divide } from "../my-tests/setup-functions.spec";
Usually, you won't see imports of spec-files because they contain tests, not functions or business logic. It should show you that something is wrong.

2022-08-02 13:15 UTC, viraxslot commented on test-jest/test-deletion.spec.ts
> +describe("Check", () => {
I'd use more descriptive name. Like "Divide operation suite" or something similar.

2022-08-02 13:15 UTC, viraxslot commented on test-jest/test-deletion.spec.ts
> +import { x } from "../setupF";
It's better to rename "x", because it's not clear what is it.

2022-08-02 13:15 UTC, viraxslot commented on test-jest/test-deletion.spec.ts
> +    const getDeletionLetters = divide(6, x);
It's an interesting idea to divide by function :) I'd set test data as near as possible to `it` function because it's easier to maintain. The exception is big test data arrays, it's better to save them in a separate file.

2022-08-02 13:15 UTC, viraxslot commented on package.json
> +    "babel": "^6.23.0",
Are you sure you need babel and core-js? :) Dependencies should include only packages in use.

2022-08-02 13:15 UTC, viraxslot commented on package.json
> +    "@types/mocha": "^9.1.1",
mocha? why?)

2022-08-02 13:15 UTC, viraxslot commented on test-jest/test-plane-name-func.spec.ts
> +    const plane = {
You use the same test data in all tests. Try to reuse it somehow. Please remember DRY principle (don't repeat yourself) and `...` operator.

2022-08-02 13:15 UTC, viraxslot commented on test-jest/test-plane-name-func.spec.ts
> +    expect(getPlaneName).toBe("The best plane is Sessna");
It a real test this check is enough. But you shouldn't remove the other checks here.

2022-08-02 18:09 UTC, AlexandraPopovaz commented on my-tests/use-functions.spec.ts
> +import * as func from './setup-functions.spec'
I got it, thank you!

2022-08-02 18:09 UTC, AlexandraPopovaz commented on test-jest/test-deletion.spec.ts
> +import { divide } from "../my-tests/setup-functions.spec";
Fixed

2022-08-02 18:09 UTC, AlexandraPopovaz commented on test-jest/test-deletion.spec.ts
> +describe("Check", () => {
Thanks, fixed!

2022-08-02 18:09 UTC, AlexandraPopovaz commented on test-jest/test-deletion.spec.ts
> +import { x } from "../setupF";
Done

2022-08-02 18:10 UTC, AlexandraPopovaz commented on package.json
> +    "babel": "^6.23.0",
I was trying to do smth with Babel and forgot to remove it :)
Fixed

2022-08-02 18:11 UTC, AlexandraPopovaz commented on package.json
> +    "@types/mocha": "^9.1.1",
It was an accident :) removed it

2022-08-02 18:12 UTC, AlexandraPopovaz commented on test-jest/test-plane-name-func.spec.ts
> +    expect(getPlaneName).toBe("The best plane is Sessna");
Yes, I got it. Thanks!

2022-08-03 07:47 UTC, AlexandraPopovaz commented on test-jest/test-plane-name-func.spec.ts
> +    const plane = {
Thanks, tried to do it

2022-08-03 07:47 UTC, AlexandraPopovaz commented on test-jest/test-deletion.spec.ts
> +    const getDeletionLetters = divide(6, x);
Changed this check. Thanks!

2022-08-03 15:11 UTC, merged