1.16 Classes tasks
AlexandraPopovaz/Simple-operations-in-js-ts pull request #21
Opened 2023-01-18 17:58 UTC by AlexandraPopovaz

2023-01-18 18:14 UTC, viraxslot requested changes

2023-01-18 18:14 UTC, viraxslot commented on src/classes/classes-task1.ts
> +    length: number;
Usually, we make all properties hidden from outside the class so you can use `private` modifier to do it. It's `public` by default.

2023-01-18 18:14 UTC, viraxslot commented on src/classes/classes-task1.ts
> +const objRectangle = new Rectangle(1, 2);
Can be just `rectangle` with lower `r` or `rect`, variable names and types are case-sensitive.

2023-01-18 18:14 UTC, viraxslot commented on src/classes/classes-task2.ts
> +    language: string;
Same here, all properties should be `private`

2023-01-18 18:14 UTC, viraxslot commented on src/classes/classes-task2.ts
> +    genre1: string;
I mean 1 genre with 3 possible values. You can use Union or Enum for that. I guess I didn't show you Enum example. But docs are here:
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types
https://www.typescriptlang.org/docs/handbook/enums.html

2023-01-18 18:14 UTC, viraxslot commented on src/classes/classes-task2.ts
> +            (this.language === language && numberOfPages - this.numberOfPages <= 10) ||
No need to add the third condition, the second one is enough.
The result of the condition is `boolean` already, you can get rid of `if` statement and return the result of the condition.

2023-01-19 15:31 UTC, AlexandraPopovaz commented on src/classes/classes-task1.ts
> +    length: number;
Fixed

2023-01-19 15:32 UTC, AlexandraPopovaz commented on src/classes/classes-task1.ts
> +const objRectangle = new Rectangle(1, 2);
Thanks, fixed

2023-01-19 15:32 UTC, AlexandraPopovaz commented on src/classes/classes-task2.ts
> +    language: string;
Fixed

2023-01-19 15:33 UTC, AlexandraPopovaz commented on src/classes/classes-task2.ts
> +    genre1: string;
Thanks! I was trying to rewrite it, but not sure that it's ok now

2023-01-19 15:33 UTC, AlexandraPopovaz commented on src/classes/classes-task2.ts
> +            (this.language === language && numberOfPages - this.numberOfPages <= 10) ||
Thanks! Done

2023-01-20 06:18 UTC, viraxslot requested changes

2023-01-20 06:18 UTC, viraxslot commented on src/classes/classes-task2.ts
> +    private Genre;
Enum creates new type, so Genre is like number or string. So it should be `private genre: Genre`

2023-01-20 06:18 UTC, viraxslot commented on src/classes/classes-task2.ts
> +        this.Genre = Genre;
Accounting the comment above here should be `this.genre = Genre.fiction` (because you have no constructor parameter to pass the value). Or you can add the parameter to be able to set genre when creating book object.

2023-01-20 10:33 UTC, AlexandraPopovaz commented on src/classes/classes-task2.ts
> +    private Genre;
Thank you! Fixed

2023-01-20 10:34 UTC, AlexandraPopovaz commented on src/classes/classes-task2.ts
> +        this.Genre = Genre;
Thanks! Fixed

2023-01-20 10:49 UTC, viraxslot approved these changes

2023-01-23 15:47 UTC, viraxslot requested changes

2023-01-23 15:47 UTC, viraxslot commented on tests/classes/test-class-rectangle-area.spec.ts
> +        expect(result).toBeNull;
False-positive, `toBeNull` function should be called. Fix in all files please.

2023-01-23 15:47 UTC, viraxslot commented on tests/classes/test-class-rectangle-area.spec.ts
> +import { Rectangle } from "../../src/classes/classes-task1";
I'd not add "test" prefix to the filename because "spec" postfix already tells us about it.
```
something.ts - code implementation
something.spec.ts - tests
```

2023-01-23 15:47 UTC, viraxslot commented on src/classes/classes-task1.ts
> +        if (this.length > 0 && this.width > 0) {
I'd use this approach, easier to read:
```
let result = null;
if (this.length > 0 && this.width > 0) {
   result = 2 * (this.length + this.width);
}

return result;
```

2023-01-23 15:47 UTC, viraxslot commented on src/classes/classes-task2.ts
> +            numberOfPages !== 0 &&
I see no problem with zeros, but ok, could be.

2023-01-23 16:19 UTC, AlexandraPopovaz commented on tests/classes/test-class-rectangle-area.spec.ts
> +        expect(result).toBeNull;
Thanks! Fixed

2023-01-23 16:19 UTC, AlexandraPopovaz commented on tests/classes/test-class-rectangle-area.spec.ts
> +import { Rectangle } from "../../src/classes/classes-task1";
Done

2023-01-23 16:19 UTC, AlexandraPopovaz commented on src/classes/classes-task1.ts
> +        if (this.length > 0 && this.width > 0) {
Thanks! It looks better, fixed.

2023-01-23 17:18 UTC, viraxslot approved these changes

2023-01-23 17:21 UTC, merged