1.17 Created parent and child classes
AlexandraPopovaz/Simple-operations-in-js-ts pull request #23
Opened 2023-01-24 16:16 UTC by AlexandraPopovaz

2023-01-25 11:44 UTC, viraxslot requested changes

2023-01-25 11:44 UTC, viraxslot commented on src/classes/classes-extends.ts
> +interface truckOptions {
We usually start types with capital letters to distinguish them from variables. truckOptions -> TruckOptions. Please fix it everywhere.

2023-01-25 11:44 UTC, viraxslot commented on src/classes/classes-extends.ts
> +    private kamazLengthRoute: number;
Why not reuse "lengthRoute" here? What's the difference between Truck and Kamaz route length? By logic, it's the same value. Kamaz properties should be unique from other truck's properties. For example, something that can have Kamaz and Scania don't.

2023-01-25 11:44 UTC, viraxslot commented on src/classes/classes-extends.ts
> +type FuelType = "petrol" | "diesel";
I'd use enum in such cases.

2023-01-25 11:44 UTC, viraxslot commented on src/classes/classes-extends.ts
> +        return this.travelTime * this.lengthRoute;
`this.lengthRoute / this.travelTime` I guess. The same below.

2023-01-25 11:44 UTC, viraxslot commented on src/classes/classes-extends.ts
> +    private kamazSpeed: number;
You already have "getSpeed" method, why do you need this data? You'll calculate it based on "route" and "time" data.

2023-01-25 11:44 UTC, viraxslot commented on src/classes/classes-extends.ts
> +    getKamazSpeed() {
We didn't touch getters and setters and it's a more natural way of do what you intended here.
You can write something like this:
```
get kamazSpeed() {
  // you should rename the property to _kamazSpeed
  return this._kamazSpeed;
}

// now your property can be accessible like
const k = new Kamaz();
k.kamazSpeed;
```

2023-01-26 18:59 UTC, AlexandraPopovaz commented on src/classes/classes-extends.ts
> +interface truckOptions {
Fixed

2023-01-26 19:00 UTC, AlexandraPopovaz commented on src/classes/classes-extends.ts
> +    private kamazLengthRoute: number;
Fixed

2023-01-26 19:00 UTC, AlexandraPopovaz commented on src/classes/classes-extends.ts
> +type FuelType = "petrol" | "diesel";
I got it. Fixed

2023-01-26 19:00 UTC, AlexandraPopovaz commented on src/classes/classes-extends.ts
> +        return this.travelTime * this.lengthRoute;
Sorry :) done

2023-01-26 19:00 UTC, AlexandraPopovaz commented on src/classes/classes-extends.ts
> +    private kamazSpeed: number;
Thanks. Fixed it

2023-01-26 19:01 UTC, AlexandraPopovaz commented on src/classes/classes-extends.ts
> +    getKamazSpeed() {
Added getters for classes. Hope it's ok now

2023-01-27 15:23 UTC, viraxslot requested changes

2023-01-27 15:23 UTC, viraxslot commented on src/classes/classes-extends.ts
> +    _weight: number;
We use `_weight` in class because property and its getter can't have the same name. Here you should use just "weight".

2023-01-27 15:23 UTC, viraxslot commented on src/classes/classes-extends.ts
> +    _fuelType: FuelType;
Same here

2023-01-27 15:23 UTC, viraxslot commented on src/classes/classes-extends.ts
> +        this.power = options.kamazSpeed;
I'd use the same name.

2023-01-27 15:23 UTC, viraxslot commented on src/classes/classes-extends.ts
> +    private _weight: number;
It's not necessary, but I'd name all private fields with _ in the beginning. Even if they don't have getters. Just for unification.

2023-01-27 16:01 UTC, AlexandraPopovaz commented on src/classes/classes-extends.ts
> +    _weight: number;
Fixed

2023-01-27 16:02 UTC, AlexandraPopovaz commented on src/classes/classes-extends.ts
> +    _fuelType: FuelType;
Thanks, fixed

2023-01-27 16:02 UTC, AlexandraPopovaz commented on src/classes/classes-extends.ts
> +        this.power = options.kamazSpeed;
Done

2023-01-27 16:02 UTC, AlexandraPopovaz commented on src/classes/classes-extends.ts
> +    private _weight: number;
Ok, fixed

2023-01-27 16:14 UTC, viraxslot approved these changes

2023-01-27 16:56 UTC, merged