1.3 conditional operators
AlexandraPopovaz/Simple-operations-in-js-ts pull request #3
Opened 2022-08-04 13:40 UTC by AlexandraPopovaz

2022-08-06 13:59 UTC, viraxslot requested changes

2022-08-06 13:59 UTC, viraxslot commented on test-jest/for-the-future.spec.ts
> +// const summ = function (a:number, b:number) {
Let's keep the code clean

2022-08-06 13:59 UTC, viraxslot commented on test-jest/optional-chaining-test.spec.ts
> +// it('Optional chaining works like a property call using a dot', () => {
Why commented?

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-conditions.ts
> +        console.log('true');
It shouldn't be a string. true and "true" are not the same. https://www.w3schools.com/js/js_booleans.asp

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-conditions.ts
> +function trueFalse(n: number) {
I'd change the function name and add the return type.

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-conditions.ts
> +    if (n < 0) {
Please use `else` here.

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-conditions.ts
> +        console.log('null');
Not "null", but null. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-conditions.ts
> +function stringfunction(string1: any, string2: any) {
Why "any"? They should be string parameters, not objects.

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-conditions.ts
> +    console.log(`${string1.value} ${string2.value}`);
Please, rewrite this https://masteringjs.io/tutorials/fundamentals/string-concat

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-conditions.ts
> +        console.log('true');
Same here with booleans

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-plane-name-func.spec.ts
> +    const planeCopy1 = { ...plane };
No need to add 1, 2, or 3 to the variable name. It's a different function and different scope. They won't affect each other. 
https://www.w3schools.com/js/js_scope.asp

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-sum1.spec.ts
> +    it('Should return negative result if a>b, a<0', () => {
a > b - wrong naming, `b` has a positive value. Please add spaces between operations (in code, in names, in comments). It's easier to read.

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-sum1.spec.ts
> +describe('Test suit for sum function', () => {
Typo, suite

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-sum1.spec.ts
> +    it("Remainder of the sum should be '0'", () => {
I don't understand the purpose of this test. You don't call the "sum" function at all, so it shouldn't be here.

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-sum1.spec.ts
> +    it("Remainder of the sum should be '1'", () => {
Same

2022-08-06 13:59 UTC, viraxslot commented on test-jest/test-conditions.ts
> +    length: 5
https://www.w3schools.com/jsref/jsref_length_string.asp

2022-08-07 14:53 UTC, AlexandraPopovaz commented on package.json
> +    "testJest1": "npx jest test-jest/test-sum.spec.ts --watchAll"
Yes, I understand it. It's only for debugging convenience

2022-08-07 14:55 UTC, AlexandraPopovaz commented on test-jest/for-the-future.spec.ts
> +// const summ = function (a:number, b:number) {
It's located in "tests for the future" file, because we decided to postpone this task (with 'sum' function). That's why I commented it

2022-08-07 14:58 UTC, AlexandraPopovaz commented on test-jest/optional-chaining-test.spec.ts
> +// it('Optional chaining works like a property call using a dot', () => {
Sorry, my bad. I was working on it and temporarily commented

2022-08-07 21:02 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +    if (n < 0) {
Fixed

2022-08-07 21:02 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +        console.log('null');
Sorry. Fixed

2022-08-07 21:02 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +function stringfunction(string1: any, string2: any) {
Done

2022-08-07 21:03 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +    console.log(`${string1.value} ${string2.value}`);
Thanks! Done

2022-08-07 21:03 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +        console.log('true');
Fixed

2022-08-07 21:03 UTC, AlexandraPopovaz commented on test-jest/test-plane-name-func.spec.ts
> +    const planeCopy1 = { ...plane };
Thanks! Fixed it

2022-08-07 21:03 UTC, AlexandraPopovaz commented on test-jest/test-sum1.spec.ts
> +    it('Should return negative result if a>b, a<0', () => {
Fixed

2022-08-07 21:04 UTC, AlexandraPopovaz commented on test-jest/test-sum1.spec.ts
> +describe('Test suit for sum function', () => {
Fixed

2022-08-07 21:04 UTC, AlexandraPopovaz commented on test-jest/test-sum1.spec.ts
> +    it("Remainder of the sum should be '0'", () => {
Removed

2022-08-07 21:04 UTC, AlexandraPopovaz commented on test-jest/test-sum1.spec.ts
> +    it("Remainder of the sum should be '1'", () => {
Removed

2022-08-07 21:04 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +    length: 5
Thanks! Done

2022-08-08 07:12 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +function trueFalse(n: number) {
I was trying..

2022-08-08 07:54 UTC, viraxslot requested changes

2022-08-08 07:54 UTC, viraxslot commented on test-jest/test-conditions.ts
> +        console.log(true);
Please remember what I said about `console.log` in functions. It's better to return value from the function and do whatever your want outside it (log value, reuse, write to file, etc.). Please use `return` instead of console.log.

2022-08-08 07:54 UTC, viraxslot commented on test-jest/test-conditions.ts
> +let length1 = string1.length;
Redundant statements I guess, you don't use length1 or length2 variables.

2022-08-08 07:54 UTC, viraxslot commented on test-jest/test-conditions.ts
> +        console.log('Hello' + ',' + ' ' + 'Alexx');
1. Return the value instead of console.log
2. Use function parameters instead of constants
3. No need to split "Hello,", it should be 1 string

2022-08-08 07:54 UTC, viraxslot commented on test-jest/test-conditions.ts
> +const getResultConcat = stringConcat(string1, string2);
I'd say function names usually contain verbs like get/set/etc., because it's an action, right? I'd use nouns/adjectives for variables, like "concatenatedString" or just "concatenated" or "concatResult".

On the other hand, your function can have the name "concatStrings".

2022-08-08 07:54 UTC, viraxslot commented on test-jest/test-conditions.ts
> +        console.log(true);
Same, please use return

2022-08-08 07:54 UTC, viraxslot commented on test-jest/test-sum1.spec.ts
> +    it('Should return negative result if a < 0, b > 0', () => {
I'd add "and abs(a) > abs(b)" to the title. Easier to understand what's the difference between this one and the next test. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/abs

2022-08-08 07:54 UTC, viraxslot commented on test-jest/optional-chaining-test.spec.ts
>  it('Optional chaining works like a property call using a dot', () => {
Please don't forget about the structure: describe -> it

2022-08-08 07:54 UTC, viraxslot commented on test-jest/optional-chaining-test.spec.ts
> +const planeSize = plane?.size ?? "Default size";
Why here? :) You shouldn't run spec-files using ts-node, only via jest. So it would be better to add only code with tests here.

2022-08-08 07:54 UTC, viraxslot commented on test-jest/test-sum1.spec.ts
> +    it('Should return positive result if a < 0, b > 0', () => {
Similar here

2022-08-08 13:39 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +        console.log(true);
Thanks! Fixed everywhere

2022-08-08 13:39 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +let length1 = string1.length;
Fixed

2022-08-08 13:40 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +        console.log('Hello' + ',' + ' ' + 'Alexx');
Done

2022-08-08 13:40 UTC, AlexandraPopovaz commented on test-jest/test-conditions.ts
> +const getResultConcat = stringConcat(string1, string2);
Thanks! Fixed

2022-08-08 13:40 UTC, AlexandraPopovaz commented on test-jest/test-sum1.spec.ts
> +    it('Should return negative result if a < 0, b > 0', () => {
Fixed

2022-08-08 13:40 UTC, AlexandraPopovaz commented on test-jest/optional-chaining-test.spec.ts
>  it('Optional chaining works like a property call using a dot', () => {
Sorry, fixed

2022-08-08 13:41 UTC, AlexandraPopovaz commented on test-jest/optional-chaining-test.spec.ts
> +const planeSize = plane?.size ?? "Default size";
Thanks! Fixed

2022-08-09 15:54 UTC, viraxslot approved these changes

2022-08-09 15:54 UTC, viraxslot commented on test-jest/test-conditions.ts
> +function getNresult(n: number): boolean | null {
I still don't like this name, because it's not descriptive at all. I even can't imagine what this function should do by it's name. But it's a minor.

2022-08-09 15:54 UTC, viraxslot commented on test-jest/test-conditions.ts
> +const ThreeParams = getThreeParams(5, 1, 10);
"concatedResult" vs "ThreeParams" - better to use camelCase format everywhere. Also minor.

2022-08-09 20:19 UTC, merged