1.9 compound conditions task3
AlexandraPopovaz/Simple-operations-in-js-ts pull request #9
Opened 2022-11-03 15:23 UTC by AlexandraPopovaz

2022-11-04 08:02 UTC, viraxslot requested changes

2022-11-04 08:02 UTC, viraxslot commented on test-jest/test-compound-conditions-task3.spec.ts
> +        //     title: "Should return null if student has a grade more than 5",
You should update `bestStudent` and check that the passed data is valid before calculating the average score. Because there is no sense, right? I'd add a separate function for that.

2022-11-04 08:02 UTC, viraxslot commented on test-jest/test-compound-conditions-task3.spec.ts
> +        //     title: "Should return null if student has a grade less than 2",
Same as before, validation checks.

2022-11-07 13:16 UTC, AlexandraPopovaz commented on my-tests/compound-conditions-func3.ts
> +function getGradeAmount(student: any) {
Fixed

2022-11-07 13:16 UTC, AlexandraPopovaz commented on my-tests/compound-conditions-func3.ts
> +    let keys = Object.keys(student ?? {});
Fixed, thanks!

2022-11-07 13:17 UTC, AlexandraPopovaz commented on my-tests/compound-conditions-func3.ts
> +console.log(bestStudent(student1, student2));
Removed

2022-11-07 13:17 UTC, AlexandraPopovaz commented on test-jest/test-compound-conditions-task3.spec.ts
> +        //     title: "Should return null if student has a grade more than 5",
Fixed. Thanks!

2022-11-07 13:17 UTC, AlexandraPopovaz commented on test-jest/test-compound-conditions-task3.spec.ts
> +        //     title: "Should return null if student has a grade less than 2",
Done

2022-11-07 16:55 UTC, viraxslot approved these changes

2022-11-07 17:45 UTC, merged